# Generated by Django 3.0.6 on 2020-05-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_auto_20200510_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jsonConfigFile', models.FileField(upload_to='')),
                ('objFile', models.FileField(upload_to='')),
            ],
        ),
    ]
