# Generated by Django 3.0.6 on 2020-05-13 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0003_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='jsonConfigFile',
            new_name='configJSONFile',
        ),
    ]
