# Generated by Django 3.0.6 on 2020-05-13 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0004_auto_20200513_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='objFile',
        ),
        migrations.CreateModel(
            name='ObjFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objFile', models.FileField(upload_to='')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.Task')),
            ],
        ),
    ]
